[package]
name = "marketplace"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "22.0.3"

[dev-dependencies]
soroban-sdk = { version = "22.0.3", features = ["testutils"] }
